### ISSUE TITLE
Release 0.1.6 contains breaking change

### ISSUE THREAD

**Issue by sosthene-nitrokey** [Sawchord/usbip-device#6]
Hi,

In release 0.1.6 you updated the version of `usb-device` to 0.3.0. However this is a breaking change because `usb-device` is part of the public API (since `UsbIpBus` implements `usb_device::UsbBus`).

This means that someone depending on `usbip-device  = "0.1.5"` and `usb-device = "0.2.9"` will end up with incompatible implementations since cargo will download version`0.1.6` of usbip-device.

The path to fixing this issue would be to:

1. Yank the release 0.1.6
2. Release the current 0.1.6 as 0.2.0, reflecting the breaking change into the version number

Thanks.

**Comment by Sawchord** [comment]
Just updated. Thanks for catching this

**Comment by sosthene-nitrokey** [comment]
Thank you very much for the quick handling.
